ktor:
  deployment:
    port: 8080
    host: 0.0.0.0
  application:
    modules: [com.example.ApplicationKt.module]

database:
  jdbcUrl: "jdbc:mysql://localhost:3306/InventarioTextiles"
  username: "root"
  password: "1234"
  driverClassName: "com.mysql.cj.jdbc.Driver"